Fixups to make WindowMaker support libs built

diff --git a/configure.ac.in b/configure.ac.in
--- a/configure.ac.in
+++ b/configure.ac.in
@@ -46,6 +46,47 @@ AC_ARG_WITH([helper-path-prefix],
             [HELPER_PATH_PREFIX="$libdir"])
 AC_SUBST([HELPER_PATH_PREFIX])
 
+_bindir=`eval echo $bindir`
+_bindir=`eval echo $_bindir`
+_libdir=`eval echo $libdir`
+_libdir=`eval echo $_libdir`
+
+X_LIBRARY_PATH=$x_libraries
+XCFLAGS="$X_CFLAGS"
+XLFLAGS="$X_LIBS"
+XLIBS="-lX11 $X_EXTRA_LIBS"
+
+lib_search_path='-L${libdir}'
+inc_search_path='-I${includedir}'
+
+dnl ===============================================
+dnl Specify paths to look for libraries and headers
+dnl ===============================================
+AC_ARG_WITH(libs-from, AS_HELP_STRING([--with-libs-from], [pass compiler flags to look for libraries]),
+	[lib_search_path="$withval $lib_search_path"])
+
+AC_ARG_WITH(incs-from, AS_HELP_STRING([--with-incs-from], [pass compiler flags to look for header files]),
+	[inc_search_path="$withval $inc_search_path"])
+
+LIBRARY_SEARCH_PATH="$lib_search_path"
+HEADER_SEARCH_PATH="$inc_search_path"
+
+AC_SUBST(LIBRARY_SEARCH_PATH)
+AC_SUBST(HEADER_SEARCH_PATH)
+
+AC_SUBST(GFXLIBS)
+AC_SUBST(ICONEXT)
+AM_CONDITIONAL([ICON_EXT_XPM],  [test "x$ICONEXT" = "xxpm"])
+AM_CONDITIONAL([ICON_EXT_TIFF], [test "x$ICONEXT" = "xtiff"])
+
+dnl Internationalization
+dnl ====================
+dnl Detect the language for translations to be installed and check
+dnl that the gettext environment works
+WM_I18N_LANGUAGES
+WM_I18N_XGETTEXT
+WM_I18N_MENUTEXTDOMAIN
+
 dnl check for UNIX variants
 AC_AIX
 AC_ISC_POSIX
@@ -64,12 +105,15 @@ LT_INIT([disable-static])
 
 dnl Check C Compiler Characteristics
 AC_C_INLINE
+WM_C_NORETURN
 
 dnl check for standard header files
 AC_HEADER_STDC
 AC_CHECK_HEADERS([stropts.h])
 AC_CHECK_FUNCS([daemon setsid])
 AC_CHECK_FUNCS(opendir)
+AC_CHECK_FUNCS(gethostname select poll strcasecmp strncasecmp \
+	       setsid mallinfo mkstemp sysconf)
 
 dnl Math lib is required (if available)
 MATH_LIBS=""
@@ -148,6 +192,41 @@ XDT_CHECK_OPTIONAL_PACKAGE([LIBSTARTUP_NOTIFICATION],
                        [startup-notification],
                        [startup notification library], [yes])
 
+dnl Math library
+dnl ============
+dnl libWINGS uses math functions, check whether usage requires linking
+dnl against libm
+WM_CHECK_LIBM
+
+dnl Check for strlcat/strlcpy
+dnl =========================
+AC_ARG_WITH([libbsd],
+  [AS_HELP_STRING([--without-libbsd], [do not use libbsd for strlcat and strlcpy [default=check]])],
+  [AS_IF([test "x$with_libbsd" != "xno"],
+    [with_libbsd=bsd]
+    [with_libbsd=]
+  )],
+  [with_libbsd=bsd])
+
+tmp_libs=$LIBS
+AC_SEARCH_LIBS([strlcat],[$with_libbsd],
+  [AC_DEFINE(HAVE_STRLCAT, 1, [Define if strlcat is available])],
+  [],
+  []
+)
+AC_SEARCH_LIBS([strlcpy],[$with_libbsd],
+  [AC_DEFINE(HAVE_STRLCAT, 1, [Define if strlcpy is available])],
+  [],
+  []
+)
+LIBS=$tmp_libs
+
+LIBBSD=
+AS_IF([test "x$ac_cv_search_strlcat" = "x-lbsd" -o "x$ac_cv_search_strlcpy" = "x-lbsd"],
+  [LIBBSD=-lbsd
+   AC_CHECK_HEADERS([bsd/string.h])]
+)
+AC_SUBST(LIBBSD)
 
 dnl
 dnl XSync support
@@ -238,6 +317,192 @@ if test x"$enable_xpresent" = x"yes"; then
 fi
 AC_SUBST([PRESENT_EXTENSION_LIBS])
 
+dnl FontConfig
+dnl ==========
+dnl libWINGS uses FcPatternDel from libfontconfig
+AC_MSG_CHECKING([for fontconfig library])
+FCLIBS=`$PKG_CONFIG fontconfig --libs`
+if test "x$FCLIBS" = "x" ; then
+        AC_MSG_RESULT([not found])
+else
+        AC_MSG_RESULT([found])
+fi
+AC_SUBST(FCLIBS)
+
+dnl Support for removing non-public symbols from a library
+dnl ======================================================
+gl_LD_VERSION_SCRIPT
+
+AC_SUBST(XLIBS)
+AC_SUBST(X_EXTRA_LIBS)
+
+WRASTER_CURRENT=6
+WRASTER_REVISION=0
+WRASTER_AGE=0
+WRASTER_VERSION=$WRASTER_CURRENT:$WRASTER_REVISION:$WRASTER_AGE
+AC_SUBST(WRASTER_VERSION)
+dnl
+dnl libWINGs
+WINGS_CURRENT=4
+WINGS_REVISION=0
+WINGS_AGE=1
+WINGS_VERSION=$WINGS_CURRENT:$WINGS_REVISION:$WINGS_AGE
+AC_SUBST(WINGS_VERSION)
+dnl
+dnl libWUtil
+WUTIL_CURRENT=5
+WUTIL_REVISION=0
+WUTIL_AGE=0
+WUTIL_VERSION=$WUTIL_CURRENT:$WUTIL_REVISION:$WUTIL_AGE
+AC_SUBST(WUTIL_VERSION)
+
+dnl Xft2 antialiased font support
+dnl =============================
+
+xft=yes
+XFTLIBS=""
+
+if test "x$PKG_CONFIG" != x -a "`$PKG_CONFIG xft; echo $?`" = 0; then
+        XFTCONFIG="$PKG_CONFIG xft"
+        pkgconfig_xft=yes
+else
+        AC_CHECK_PROG(XFTCONFIG, xft-config, xft-config)
+fi
+
+AC_MSG_CHECKING([for the Xft2 library])
+
+if test "x$XFTCONFIG" != x; then
+        XFTLIBS=`$XFTCONFIG --libs`
+        XFTFLAGS=`$XFTCONFIG --cflags`
+        AC_MSG_RESULT([found])
+else
+        AC_MSG_RESULT([not found])
+        echo
+        echo "ERROR!!! libXft2 is not installed or could not be found."
+        echo "         Xft2 is a requirement for building Window Maker."
+        echo "         Please install it (along with fontconfig) before continuing."
+        echo
+        exit 1
+fi
+
+minXFT="2.1.0"
+goodxft="no"
+
+dnl
+dnl The macro below will use $XFTFLAGS (defined above) to find Xft.h
+dnl
+WM_CHECK_XFT_VERSION($minXFT, goodxft=yes, goodxft=no)
+
+if test "$goodxft" = no; then
+        echo
+        echo "ERROR!!! libXft on this system is an old version."
+        echo "         Please consider upgrading to at least version ${minXFT}."
+        echo
+        exit 1
+fi
+
+AC_SUBST(XFTFLAGS)
+AC_SUBST(XFTLIBS)
+
+dnl X Misceleanous Utility
+dnl ======================
+dnl the libXmu is used in WRaster
+WM_EXT_CHECK_XMU
+
+dnl GIF Support
+dnl ============
+AC_ARG_ENABLE(gif,
+    [AS_HELP_STRING([--disable-gif], [disable GIF support through libgif or libungif])],
+    [AS_CASE(["$enableval"],
+        [yes|no], [],
+        [AC_MSG_ERROR([bad value $enableval for --enable-gif])] )],
+    [enable_gif=auto])
+WM_IMGFMT_CHECK_GIF
+
+dnl TIFF Support
+dnl ============
+AC_ARG_ENABLE([tiff],
+    [AS_HELP_STRING([--disable-tiff], [disable use of TIFF images through libtiff])],
+    [AS_CASE(["$enableval"],
+        [yes|no], [],
+        [AC_MSG_ERROR([bad value $enableval for --enable-tiff])] )],
+    [enable_tiff=auto])
+WM_IMGFMT_CHECK_TIFF
+
+
+dnl WEBP Support
+dnl ============
+AC_ARG_ENABLE([webp],
+    [AS_HELP_STRING([--disable-webp], [disable WEBP support through libwebp])],
+    [AS_CASE(["$enableval"],
+        [yes|no], [],
+        [AC_MSG_ERROR([bad value $enableval for --enable-webp])] )],
+    [enable_webp=auto])
+WM_IMGFMT_CHECK_WEBP
+
+
+dnl MagicK Support
+dnl ==============
+AC_ARG_ENABLE([magick],
+    [AS_HELP_STRING([--disable-magick], [disable MAGICK support through libMagickWand])],
+    [AS_CASE(["$enableval"],
+        [yes|no], [],
+        [AC_MSG_ERROR([bad value $enableval for --enable-magick])] )],
+    [enable_magick=auto])
+WM_IMGFMT_CHECK_MAGICK
+
+dnl JPEG Support
+dnl ============
+AC_ARG_ENABLE([jpeg],
+    [AS_HELP_STRING([--disable-jpeg], [disable JPEG support through libjpeg])],
+    [AS_CASE(["$enableval"],
+        [yes|no], [],
+        [AC_MSG_ERROR([bad value $enableval for --enable-jpeg])] )],
+    [enable_jpeg=auto])
+WM_IMGFMT_CHECK_JPEG
+
+dnl PNG Support
+dnl ===========
+AC_ARG_ENABLE([png],
+    [AS_HELP_STRING([--disable-png], [disable PNG support through libpng])],
+    [AS_CASE(["$enableval"],
+        [yes|no], [],
+        [AC_MSG_ERROR([bad value $enableval for --enable-png])] )],
+    [enable_png=auto])
+WM_IMGFMT_CHECK_PNG
+
+dnl XPM Support
+dnl ===========
+AC_ARG_ENABLE([xpm],
+    [AS_HELP_STRING([--disable-xpm], [disable use of XPM pixmaps through libXpm])],
+    [AS_CASE(["$enableval"],
+        [yes|no], [],
+        [AC_MSG_ERROR([bad value $enableval for --enable-xpm])] )],
+    [enable_xpm=auto])
+WM_IMGFMT_CHECK_XPM
+
+dnl PANGO support
+dnl =============
+pango=no
+AC_ARG_ENABLE(pango, AS_HELP_STRING([--enable-pango], [enable Pango text layout support]),
+                pango=$enableval, pango=no)
+
+PANGOFLAGS=
+PANGOLIBS=
+if test "$pango" = yes; then
+	PANGOLIBS=`$PKG_CONFIG pangoxft --libs`
+	PANGOFLAGS=`$PKG_CONFIG pangoxft --cflags`
+	if test "x$PANGOLIBS" = "x" ; then
+	        AC_MSG_RESULT([not found])
+	else
+		AC_DEFINE(USE_PANGO, 1, [Define if Pango is to be used])
+		AC_MSG_RESULT([found])
+	fi
+fi
+inc_search_path="$inc_search_path $PANGOFLAGS"
+AC_SUBST(PANGOLIBS)
+
+
 dnl
 dnl Xcomposite and related extensions
 dnl
@@ -288,26 +553,36 @@ fi
 AC_DEFINE_UNQUOTED([REVISION], "$REVISION", [git id])
 AC_SUBST([REVISION])
 
-AC_OUTPUT([
-Makefile
-defaults/Makefile
-helper-dialog/Makefile
-icons/Makefile
-icons/22x22/Makefile
-icons/48x48/Makefile
-icons/scalable/Makefile
-po/Makefile.in
-common/Makefile
-settings-dialogs/Makefile
-src/Makefile
-themes/Makefile
-themes/daloa/Makefile
-themes/default/Makefile
-themes/default-hdpi/Makefile
-themes/default-xhdpi/Makefile
-themes/kokodi/Makefile
-themes/moheli/Makefile
-])
+AC_CONFIG_FILES(
+    Makefile
+    defaults/Makefile
+    helper-dialog/Makefile
+    icons/Makefile
+    icons/22x22/Makefile
+    icons/48x48/Makefile
+    icons/scalable/Makefile
+    po/Makefile.in
+    common/Makefile
+    settings-dialogs/Makefile
+    src/Makefile
+    themes/Makefile
+    themes/daloa/Makefile
+    themes/default/Makefile
+    themes/default-hdpi/Makefile
+    themes/default-xhdpi/Makefile
+    themes/kokodi/Makefile
+    themes/moheli/Makefile
+
+   dnl WRaster Library
+    wrlib/Makefile
+    wrlib/tests/Makefile
+
+    dnl WINGs toolkit
+    WINGs/Makefile WINGs/WINGs/Makefile WINGs/po/Makefile
+    WINGs/Documentation/Makefile WINGs/Resources/Makefile WINGs/Extras/Makefile
+    WINGs/Examples/Makefile WINGs/Tests/Makefile
+)
+AC_OUTPUT
 
 echo
 echo "Build Configuration for $PACKAGE version $VERSION revision $REVISION:"
